# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-24 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('login', models.CharField(max_length=255)),
                ('node_id', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=255)),
                ('gravatar_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('html_url', models.CharField(max_length=255)),
                ('followers_url', models.CharField(max_length=255)),
                ('following_url', models.CharField(max_length=255)),
                ('gists_url', models.CharField(max_length=255)),
                ('starred_url', models.CharField(max_length=255)),
                ('subscriptions_url', models.CharField(max_length=255)),
                ('organizations_url', models.CharField(max_length=255)),
                ('repos_url', models.CharField(max_length=255)),
                ('events_url', models.CharField(max_length=255)),
                ('received_events_url', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('site_admin', models.BooleanField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('creation_date',),
            },
        ),
    ]
