# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-24 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubUsers', '0002_auto_20180624_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='gravatar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
