# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('githubUsers', '0003_auto_20180624_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='updation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
