# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-26 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('githubUsers', '0010_auto_20180626_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='db_entry_creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
