# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubUsers', '0011_auto_20180626_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='html_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
