# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-26 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubUsers', '0012_auto_20180626_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
