# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-27 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubUsers', '0013_auto_20180627_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackApiUsage',
            fields=[
                ('serach_entry', models.AutoField(primary_key=True, serialize=False)),
                ('api_usage_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSummary',
            fields=[
            ],
            options={
                'verbose_name': 'User Summary',
                'proxy': True,
                'verbose_name_plural': 'Users Summary',
            },
            bases=('githubUsers.userdetail',),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='db_entry_creation_date',
            field=models.DateTimeField(),
        ),
    ]
