# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-27 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubUsers', '0014_auto_20180627_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackapiusage',
            old_name='serach_entry',
            new_name='search_entry',
        ),
    ]
