# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-27 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubUsers', '0015_auto_20180627_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsageSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Search API Usage Summary',
                'verbose_name_plural': 'Search API Usage Summary',
                'proxy': True,
            },
            bases=('githubUsers.trackapiusage',),
        ),
    ]
